export declare const HOME: string;
export declare const PATHS: {
    userCaches: string;
    systemCaches: string;
    userLogs: string;
    systemLogs: string;
    tmp: string;
    varFolders: string;
    trash: string;
    downloads: string;
    documents: string;
    chromeCacheDefault: string;
    chromeCache: string;
    safariCache: string;
    firefoxProfiles: string;
    arcCache: string;
    npmCache: string;
    yarnCache: string;
    pnpmCache: string;
    pipCache: string;
    xcodeDerivedData: string;
    xcodeArchives: string;
    xcodeSimulators: string;
    cocoapodsCache: string;
    gradleCache: string;
    cargoCache: string;
    iosBackups: string;
    mailDownloads: string;
    applications: string;
};
export declare function expandPath(path: string): string;
export declare function isSystemPath(path: string): boolean;
//# sourceMappingURL=paths.d.ts.map